2025-10-04T00:18:01.226547908Z Neon One Widget Package initialized for CMS integration
2025-10-04T00:18:01.226549928Z ‚úÖ Loaded 49 orchid ecosystem records
2025-10-04T00:18:01.226551948Z üîó Orchid Interaction Explorer routes registered successfully
2025-10-04T00:18:01.226554119Z Orchid Interaction Explorer system initialized
2025-10-04T00:18:01.226556649Z üìä System Monitor Dashboard initialized
2025-10-04T00:18:01.226558909Z System Monitor Dashboard initialized
2025-10-04T00:18:01.226561279Z Orchid Games initialization error: View function mapping is overwriting an existing endpoint function: games.leaderboard
2025-10-04T00:18:01.22656362Z API v2 routes initialized - FastAPI-compatible endpoints available
2025-10-04T00:18:01.22656588Z Taxonomy Verification system initialized
2025-10-04T00:18:01.22656883Z AI Collection Manager initialization error: The name 'collection_manager' is already registered for this blueprint. Use 'name=' to provide a unique name.
2025-10-04T00:18:01.22657204Z Breeder Pro+ Orchestrator initialization error: CRITICAL: Failed to initialize base integration: CRITICAL: Google Cloud integration not functional - check credentials and API access
2025-10-04T00:18:01.22657475Z üîç SVO Analysis web interface initialized
2025-10-04T00:18:01.226577381Z OrchidAI Research Hub initialization error: The name 'research_hub' is already registered for this blueprint. Use 'name=' to provide a unique name.
2025-10-04T00:18:01.226580081Z üåø Trefle Ecosystem Enrichment admin interface initialized
2025-10-04T00:18:01.226582621Z 127.0.0.1 - - [04/Oct/2025:00:18:01 +0000] "HEAD / HTTP/1.1" 500 0 "-" "-"
2025-10-04T00:18:01.226590682Z     server_error = self.ensure_sync(handler)(server_error)
2025-10-04T00:18:01.226597992Z   File "/opt/render/project/src/routes.py", line 6160, in internal_error
2025-10-04T00:18:01.226600482Z     return render_template('500.html'), 500
2025-10-04T00:18:01.226602712Z            ~~~~~~~~~~~~~~~^^^^^^^^^^^^
2025-10-04T00:18:01.226604892Z   File "/opt/render/project/src/.venv/lib/python3.13/site-packages/flask/templating.py", line 150, in render_template
2025-10-04T00:18:01.226607023Z     return _render(app, template, context)
2025-10-04T00:18:01.226609723Z   File "/opt/render/project/src/.venv/lib/python3.13/site-packages/flask/templating.py", line 131, in _render
2025-10-04T00:18:01.226627284Z     rv = template.render(context)
2025-10-04T00:18:01.226630105Z   File "/opt/render/project/src/.venv/lib/python3.13/site-packages/jinja2/environment.py", line 1295, in render
2025-10-04T00:18:01.226632115Z     self.environment.handle_exception()
2025-10-04T00:18:01.226634335Z     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
2025-10-04T00:18:01.226636545Z   File "/opt/render/project/src/.venv/lib/python3.13/site-packages/jinja2/environment.py", line 942, in handle_exception
2025-10-04T00:18:01.226638665Z     raise rewrite_traceback_stack(source=source)
2025-10-04T00:18:01.226641285Z   File "/opt/render/project/src/templates/500.html", line 1, in top-level template code
2025-10-04T00:18:01.226643586Z     {% extends "base.html" %}
2025-10-04T00:18:01.226645706Z   File "/opt/render/project/src/templates/base.html", line 338, in top-level template code
2025-10-04T00:18:01.226648036Z     <li><a class="dropdown-item py-2" href="{{ url_for('replit_auth.login') }}" style="color: #20c997; font-weight: bold;">
2025-10-04T00:18:01.226650086Z     ^
2025-10-04T00:18:01.226652206Z   File "/opt/render/project/src/.venv/lib/python3.13/site-packages/flask/app.py", line 1121, in url_for
2025-10-04T00:18:01.226654306Z     return self.handle_url_build_error(error, endpoint, values)
2025-10-04T00:18:01.226656416Z            ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
2025-10-04T00:18:01.226658727Z   File "/opt/render/project/src/.venv/lib/python3.13/site-packages/flask/app.py", line 1110, in url_for
2025-10-04T00:18:01.226660847Z     rv = url_adapter.build(  # type: ignore[union-attr]
2025-10-04T00:18:01.226663417Z         endpoint,
2025-10-04T00:18:01.226665627Z     ...<3 lines>...
2025-10-04T00:18:01.226667717Z         force_external=_external,
2025-10-04T00:18:01.226669837Z     )
2025-10-04T00:18:01.226671948Z   File "/opt/render/project/src/.venv/lib/python3.13/site-packages/werkzeug/routing/map.py", line 924, in build
2025-10-04T00:18:01.226674028Z     raise BuildError(endpoint, values, method, self)
2025-10-04T00:18:01.226676178Z werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'replit_auth.login'. Did you mean 'auth.login' instead?
2025-10-04T00:18:03.791894375Z ==> Your service is live üéâ
2025-10-04T00:18:03.822521331Z ==> 
2025-10-04T00:18:03.849324108Z ==> ///////////////////////////////////////////////////////////
2025-10-04T00:18:03.875214944Z ==> 
2025-10-04T00:18:03.904126551Z ==> Available at your primary URL https://orchid-continuum-1.onrender.com
2025-10-04T00:18:04.120870783Z ==> 
2025-10-04T00:18:04.146503619Z ==> ///////////////////////////////////////////////////////////